#!/bin/bash

# uses a regular expression to determine validity of a variable name.
# invoked via ./valid
for arg in "$@"
do
	if echo $arg | grep -q '^[a-zA-Z][a-zA-Z0-9]*'; then
		echo "yes"
	else
		echo "no"
	fi	
done
