ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
ls -l /home/ian/ | grep -o g
