#!/bin/bash
# Ian Schweer
# 22514022

trash=$TRASH
echo "The trash var is $TRASH"
if [[ "$TRASH" == "" ]]; then
	echo "The trash variable is not currently set. Consider setting an enviornment variable. Assuming ~/.Trash"
	trash="$HOME/.Trash"
fi

if [ ! -e $trash ]; then
	mkdir $trash
fi

ls -l $trash
