#!/bin/bash

# do we have any options?
flags=0
usel=1
useS=1
flagdata=""
while getopts ":ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1" var; do
	flags=1
	case $var in
		l)
			usel=0
			flagdata="$flagdata$var"
			;;
		S)
			useS=0
			flagdata="$flagdata$var"
			;;
		s)
			echo "Ignoring s">&2
			;;
		i)
			echo "Ignoring i">&2
			;;
		g)
			echo "Ignoring g">&2
			;;
		1)
			echo "Ignoring 1">&2
			;;
		x)
			echo "Ignoring x">&2
			;;
		s)
			echo "Ignoring s">&2
			;;
		C)
			echo "Ignoring C">&2
			;;
		d)
			echo "Ignoring d">&2
			;;
		m)
			echo "Ignoring m">&2
			;;
		1)
			echo "Ignoring 1">&2
			;;
		*)
			echo "Option $var was found"
			flagdata="$flagdata$var"
			;;
	esac
done
shift `expr $OPTIND - 1`
echo "all args are $@"
# Very simple script, using the -lS commands to sort the output
if [[ $flags -eq 1 ]]; then
	if [[ $useS -eq 1 ]]; then
		#statements
		flagdata="S$flagdata"
	fi
	if [[ $usel -eq 1 ]]; then
		flagdata="l$flagdata"
	fi
	echo "All flags are $flagdata"
	ls "-$flagdata" "$@" | grep ^-
else
	# default behavior
	ls -lS "$@" | grep ^-
fi
