#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Not enough args. Please enter a filename"
fi
for file in "$@"
do
	# very carefully get the file name only, will maintaing spaces
	thefilename=$(basename "$file")
	trashpath="$HOME/.Trash/$thefilename"
	echo $trashpath
	if [ -f "$file" ]; then
		echo "$file is a regular file"	

		# the file exists and can be safe rm'd
		# TODO: Refactor this to use a login variable.
		mv "$file" "$trashpath"
	elif [ -d "$file" ]; then
		echo "$file is a directory"
		#TODO: See TODO@1		
		mv "$file" "$trashpath"
	else
		echo "$file cannot be srm'd"
	fi
done
