#!/bin/bash
# Ian Schweer
# 22514022

trash=$TRASH
if [[ "$trash" == "" ]]; then
	echo "The trash variable is not currently set. Consider setting an enviornment variable. Assuming ~/.Trash"
	trash="$HOME/.Trash"
fi

if [ ! -e $trash ]; then
	mkdir $trash
fi

eval mv "$trash/*" "."
