#!/bin/bash

error()  {
	echo $1 >&2
	cleanup
	exit $2
}

# prepare
#	prepares our compelation process
prepare() {
	if [ ! -f $1 ]; then
		error "File $1 does not exist" -1
	fi
	tmp=`mktemp -dt $1`
}

# interpret
#	runs the compiler on the .c file and executes it.
interpret() {
	execname=$1
	filename=$2
	scriptloc=$3
	tmpdir=$4
	shift 3
	/usr/bin/gcc -o "$tmpdir/$execname" "$scriptloc/$filename";
	if [[ $? -eq 0 ]]; then
		$tmpdir/$execname "$@" 
	else
		error "Error in gcc compiler" -3
	fi
}

# cleanup
#	cleanup the resulting files in the tmp directory
cleanup() {
	echo "cleanup"
	#/bin/rm -rf $tmp
}

cprog="$0.c"
prepare $cprog
interpret $0 $cprog $PWD $tmp "$@"
cleanup
